name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        sudo apt-get update  -y && apt-get install  wget libxslt1-dev libxml2-dev zlib1g-dev libpcre3-dev libbz2-dev libssl-dev make -y
        tar -xf nginx-module-vts.tar.gz
        #wget http://nginx.org/download/nginx-1.22.0.tar.gz
        tar -xf nginx-1.22.0.tar.gz
        cd nginx-1.22.0
        wget https://www.openssl.org/source/old/1.0.2/openssl-1.0.2k.tar.gz
        tar -xf openssl-1.0.2k

        ./configure  \
            --conf-path=/etc/nginx/nginx.conf  --prefix=/usr/share/nginx \
            --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log \
            --pid-path=/run/nginx.pid \
            --with-cc-opt="-static -static-libgcc" \
            --with-ld-opt="-static" --with-cpu-opt=generic --with-pcre \
            --with-mail --with-ipv6 --with-poll_module --with-select_module \
            --with-select_module --with-poll_module \
            --with-http_ssl_module --with-http_realip_module \
            --with-http_v2_module \
            --with-http_addition_module --with-http_sub_module --with-http_dav_module \
            --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module \
            --with-http_gzip_static_module --with-http_auth_request_module \
            --with-http_random_index_module --with-http_secure_link_module \
            --with-http_degradation_module --with-http_stub_status_module \
            --with-mail --with-mail_ssl_module --with-openssl=./openssl-* \
            --add-module=../nginx-module-vts-master && make -j1 && cp objs/nginx /tmp/nginx
        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        # secrets.GITHUB_TOKEN 是内置变量
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /tmp/nginx
        asset_name: mything
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
